stages:
   - build
   - deploy


build ryd:  
   image: node:latest
   stage: build  
   only:    
      - main  
   script:
      - "cd frontend/relaxandenjoy"  
      - npm install      
      - npm run build  
   artifacts:    
      paths:          
         - frontend/relaxandenjoy/dist/    
      expire_in: 2 hour



deploy ryd:
   image: python:latest
   stage: deploy
   only:
      - main
   script:
      - pip install --upgrade pip
      - pip install awscli
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws s3 sync frontend/relaxandenjoy/dist/ s3://$FRONTEND_S3