stages:
   - build
   - deploy


build prod:  
   image: node:latest
   stage: build  
   only:    
      - main  
   script:
      - cd grupo-05/frontend/    
      - npm install      
      - npm run build  
   artifacts:    
      paths:          
         - dist/    
      expire_in: 2 hour



deploy ryd:
   image: python:latest
   stage: deploy
   only:
      - main
   script:
      - pip3 install awscli
      - aws s3 sync ./build s3://$FRONTEND_S3