deploy frd:
  stage: deploy
  when: manual
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
    entrypoint: [""]
  script: 
    -aws configure set region us-east-2
    -aws s3 cp frontend/relaxandenjoy/ s3://$FRONTEND_S3
