// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateproductTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createproduct() {
    driver.get("http://localhost:5173/Home");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Inciar sesión")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("prueba@prueba.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("admin1");
    driver.findElement(By.cssSelector(".cursor-pointer")).click();
    driver.findElement(By.linkText("Administración")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Hotel nuevohotel");
    driver.findElement(By.id("category")).click();
    {
      WebElement dropdown = driver.findElement(By.id("category"));
      dropdown.findElement(By.xpath("//option[. = 'Hoteles']")).click();
    }
    driver.findElement(By.name("location")).click();
    driver.findElement(By.name("location")).sendKeys("Playa linda");
    driver.findElement(By.name("popularity")).click();
    driver.findElement(By.name("popularity")).sendKeys("4");
    driver.findElement(By.id("address")).click();
    driver.findElement(By.id("address")).sendKeys("Calle 100");
    driver.findElement(By.id("city")).click();
    {
      WebElement dropdown = driver.findElement(By.id("city"));
      dropdown.findElement(By.xpath("//option[. = 'San Andres']")).click();
    }
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).sendKeys("Hermoso hotel");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("soy la descripcion");
    driver.findElement(By.id("Baño")).click();
    driver.findElement(By.id("Baño")).sendKeys("1");
    driver.findElement(By.id("Baño")).click();
    driver.findElement(By.id("Balcon")).click();
    driver.findElement(By.id("Cocina")).click();
    driver.findElement(By.cssSelector(".flex:nth-child(4)")).click();
    driver.findElement(By.id("Televisor")).click();
    driver.findElement(By.id("Habitacion")).click();
    driver.findElement(By.id("Habitacion")).sendKeys("1");
    driver.findElement(By.id("Habitacion")).click();
    driver.findElement(By.id("Habitacion")).sendKeys("2");
    driver.findElement(By.id("Habitacion")).click();
    driver.findElement(By.id("rules")).click();
    driver.findElement(By.id("rules")).sendKeys("No dejar basura");
    driver.findElement(By.id("healthAndSafety")).click();
    driver.findElement(By.id("healthAndSafety")).sendKeys("Usar mascarilla");
    driver.findElement(By.id("politics")).click();
    driver.findElement(By.id("politics")).sendKeys("Solo cinco dias antes");
    driver.findElement(By.cssSelector(".fa-file-arrow-up")).click();
    driver.findElement(By.id("images")).sendKeys("C:\\fakepath\\hotel-de-cinco-estrellas-en-las-islas-maldivas-maldives-5-star-resort-1920x1200-wallpaper.jpg");
    driver.findElement(By.cssSelector(".w-80")).click();
    driver.findElement(By.cssSelector(".w-14")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".w-14"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".w-full:nth-child(8) .min-h-10")).click();
  }
}
