// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchbycityTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchbycity() {
    driver.get("http://localhost:5173/Home");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.name("city")).click();
    {
      WebElement dropdown = driver.findElement(By.name("city"));
      dropdown.findElement(By.xpath("//option[. = 'Bogota']")).click();
    }
    driver.findElement(By.cssSelector(".ant-picker-input-active > input")).click();
    driver.findElement(By.cssSelector(".ant-picker-panel:nth-child(1) tr:nth-child(1) > .ant-picker-cell:nth-child(5) > .ant-picker-cell-inner")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) > .ant-picker-cell-range-hover-end > .ant-picker-cell-inner")).click();
    driver.findElement(By.cssSelector(".tablet\\3Atext-lg")).click();
  }
}
