// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SuccessfulreservationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void successfulreservation() {
    driver.get("http://localhost:5173/Login");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("hola@prueba.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123456");
    driver.findElement(By.cssSelector(".cursor-pointer")).click();
    driver.findElement(By.cssSelector(".w-full:nth-child(4) .min-h-10")).click();
    js.executeScript("window.scrollTo(0,67.19999694824219)");
    driver.findElement(By.cssSelector(".h-9")).click();
    js.executeScript("window.scrollTo(0,67.19999694824219)");
    driver.findElement(By.id("countries")).click();
    {
      WebElement dropdown = driver.findElement(By.id("countries"));
      dropdown.findElement(By.xpath("//option[. = 'Medellin']")).click();
    }
    driver.findElement(By.cssSelector(".w-full > .ant-picker-input > input")).click();
    driver.findElement(By.linkText("Now")).click();
    driver.findElement(By.cssSelector(".ant-picker-range")).click();
    driver.findElement(By.cssSelector(".ant-picker-input-active > input")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) > .ant-picker-cell-end:nth-child(3) > .ant-picker-cell-inner")).click();
    driver.findElement(By.cssSelector(".ant-picker-cell-range-hover-edge-start > .ant-picker-cell-inner")).click();
    driver.findElement(By.cssSelector(".px-4")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".px-4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
